[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.33.20"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[constraint]]
  branch = "master"
  name = "github.com/skarademir/naturalsort"

[[constraint]]
  name = "github.com/intel-go/cpuid"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
